---
galaxy_info:
  role_name: acme_certificate
  author: Felix Fontein
  description: >
    Wrapper of Ansible's included acme_certificate module, whose aim is that almost no code
    is executed on the webserver.

  license: MIT

  min_ansible_version: 2.9.10

  galaxy_tags:
  - acme
  - letsencrypt
  - buypass
  - ssl
  - tls
  - https
  - encryption
  - security
  - web
  - certificate

dependencies: []
